### PR TITLE
Added cmake files to build elfio

### PR DESCRIPTION
**Pull request by muman613**
This Pull Request adds `CMakeLists.txt` files to the ELFIO project facilitating building using the cmake build configuration tool. While autotools is a well accepted method of configuring build systems, cmake has become just as popular in many use-cases.

Please consider this PR for merging with the master branch.

### CODE REVIEW

**Comment by serge1** [comment]
The build system has a little significance for a header-only library. (Why not Meson, for example). But, you did the work and the maintenance is not big. So, accepted and merged. Thank you!

**Comment by muman613** [comment]
Thank you @serge1 , I use the CLion IDE and have been using ELFIO in a project at IBM so I figured I'd give back to the community. Love the library and thanks for the good work.

**Comment by pavelkryukov** [comment]
@serge1 In CMake, you may list an external Git repository as a dependency, eliminating a need to copy headers and/or keep them in a Git submodule.
Thank you @muman613, I'll switch my project to that mode!

**Comment by serge1** [comment]
Thank you @muman613  for your compliments! It is good to know that ELFIO is in use in IBM too!

**Pull request merged**
