### PR TITLE
Add insert_data() to section

### PR DESCRIPTION
**Pull request by covanam**
I'm working on a ELF patching library, and I find myself with the need for inserting some data in the middle of the section. I have to use `set_data()`, but it would be nice if there is built-in support from ELFIO.

This implementation is largely based on existing `append_data()` functions.

### CODE REVIEW

**Comment by serge1** [comment]
Thank you for your submission!

`insert_data()` and `append_data()` have practically the same implementation. Would not it be nicer to add 'position' argument to `append_data()` as an optional argument defaulting to 'append at the end'?

**Comment by covanam** [comment]
> Thank you for your submission!
> 
> `insert_data()` and `append_data()` have practically the same implementation. Would not it be nicer to add 'position' argument to `append_data()` as an optional argument defaulting to 'append at the end'?

Thanks for the review.

Yes I agree that it makes sense to merge the implementations together. However, in my opinion, adding argument `position` to `append_data` is not a good idea, because the function name gives the impression that data will be put at the end, and it may be confusing that an append function can also insert data in the middle.

Perhaps it is better to keep both `append_data` and `insert_data`. We can have `append_data` calling `insert_data`, with `position` argument being set to the end. What do you think?

**Comment by serge1** [comment]
> We can have `append_data` calling `insert_data`, with `position` argument being set to the end. What do you think?

Yes, I think it will be better.

Now, are you going to implement such solution or are expecting it from me. The effort is not big, so, I don't care much.

**Comment by covanam** [comment]
I have pushed a new commit for this.

**Comment by serge1** [comment]
Accepted. Thank you very much!

**Pull request closed without merging**
