### PR TITLE
Update elfio.hpp

### PR DESCRIPTION
**Pull request by tgotic**
Enable loading of wide char file names.

### CODE REVIEW

**Comment by serge1** [comment]
Could you please explain the intention of this commit and what kind of problems it addresses?

**Comment by serge1** [comment]
The problem with such approach is that it breaks library's API backward compatibility

**Comment by tgotic** [comment]
I'm loading elf file with unicode (UTF-16) name. So I need function that accepts wstring. 
There are two possibilities:
new load function `bool load(const std::wstring& file_name)` 
or `template <typename T> bool load( const std::basic_string<T>& file_name )`.
Maybe first option would be better?

**Comment by serge1** [comment]
Yes, the first option with explicit type would be better. But, then, `stream.open()` would require casting to `const char* s` anyhow. Such casting can be done at a caller level.

**Comment by serge1** [comment]
I'm closing this PR. If you have more information regarding it, please feel free to reopen.

**Pull request closed without merging**
